name: Setup Reviewdog for Rails
inputs:
  use_rubocop:
    required: false
    default: false
    type: boolean
  use_brakeman:
    required: false
    default: false
    type: boolean
  github_token:
    required: true
    default: ""
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup reviewdog/rubocop
      if: ${{ inputs.use_rubocop == true }}
      uses: reviewdog/action-rubocop@v2
      with:
        github_token: ${{ inputs.github_token }}
        rubocop_version: gemfile
        rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
        reporter: github-pr-review
        fail_on_error: true
    - name: Setup reviewdog/brakeman
      if: ${{ inputs.use_brakeman == true }}
      uses: reviewdog/action-brakeman@v2
      with:
        github_token: ${{ inputs.github_token }}
        reporter: github-pr-review
        fail_on_error: true
