name: Test reviewdog_rails.yml

on:
  pull_request:
    branches:
      - "*"

jobs:
  test-reviewdog-rails:
    uses: ./.github/workflows/reviewdog_rails.yml
    with:
      ruby_version: 3.1.0
      use_rubocop: true
      use_brakeman: false
    secrets:
      github_pat: ${{ secrets.GITHUB_TOKEN }}
