name: Test cd.yml

on:
  pull_request:
    branches:
      - "*"

jobs:
  test-cd:
    uses: pinnacles/common-cicd-actions/.github/workflows/cd.yml@test-cd
    with:
      use_ruby: true
      ruby_version: 3.1.0
      use_node: true
      node_version: 17.4.0
      node_package_manager: "yarn"
      use_go: false
      go_version: ""
    secrets:
      github_pat: ""
      aws_region: ${{ secrets.AWS_REGION }}
      aws_iam_role: ${{ secrets.AWS_IAM_ROLE }}
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY }}
