name: Test reviewdog_js.yml

on:
  pull_request:
    branches:
      - "*"

jobs:
  test-reviewdog-js:
    uses: ./.github/workflows/reviewdog_js.yml
    with:
      node_version: 17.4.0
      use_eslint: true
    secrets:
      github_pat: ${{ secrets.GITHUB_TOKEN }}
